steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'node'
  id: run test again with node from Docker hub, which is the new recommended way
  entrypoint: 'npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/npm'
  id: run test with a node version in cloud-builders/npm has a problem
  entrypoint: bash
  args:
  - '-c'
  - |
    node --version
    npm --version
    npm run test
